apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-replica
  labels:
    app: redis
    role: replica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: replica
  template:
    metadata:
      labels:
        app: redis
        role: replica
    spec:
      containers:
      - name: replica
        image: redis:6.0.5
        args: ["--slaveof", "redis-master", "6379"]
        ports:
        - containerPort: 6379
